{{- define "_snippet-labels" -}}
app.kubernetes.io/name: {{ .Values.metadata.appName }}
app.kubernetes.io/instance: '{{ .Values.metadata.appName }}-{{ .Values.metadata.branch }}'
app.kubernetes.io/component: {{ .Values.metadata.component }}
app.kubernetes.io/part-of: {{ .Values.metadata.partOf }}
app.kubernetes.io/managed-by: argocd
{{- end -}}

{{- define "_snippet-labels-version" -}}
app.kubernetes.io/version: {{ .Values.container.image.tag }}
{{- end -}}
