nameOverride: argocd
fullnameOverride: "argocd"

crds:
  install: true
  keep: true

global:
  image:
    repository: quay.io/argoproj/argocd
    tag: "v2.6.2"
  logging:
    format: json
    level: info


configs:
  cm:
    url: "https://argo.iis-dev.net"
    exec.enabled: "true"
    # kustomize.buildOptions: "--enable-alpha-plugins"
    # helm.valuesFileSchemes: >-
    #   secrets+gpg-import, secrets+gpg-import-kubernetes,
    #   secrets+age-import, secrets+age-import-kubernetes,
    #   secrets,secrets+literal,
    #   https
    helm.valuesFileSchemes: >-
      secrets+gpg-import, secrets+gpg-import-kubernetes,
      secrets,secrets+literal,
      https
  rbac:
    policy.csv: |
        p, role:readonly, applications, sync, */*, allow
        g, platform, role:admin
    policy.default: role:readonly

  params:
    server.insecure: true
  # vraj na githube to netreba
  # knownHosts:
  #   data:
  #     ssh_known_hosts: |
  #       gilab.techmates.io ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFLH6wA6K6HpKTeyCKmEEk7BvU/BVyHHQ1qev2PQEEhlBJM7g6KXFzqYOuVdvpUHy07K6koF7Y2eKvyjUgR/U2UGN5CTkpjb/FoKP813SGSCvypXEpTdHCWWKcEWRed6XZG+EClf+Zqnx1uos/wWisTKvt6IeyKsub78gdLlYiDlICvlZFQLlervwfE0B1JXCJT8J48rnRHb8nuNYZAcuazhfXtbKC5Ankgvizwd0A+YTqRX2kKXgWVxODsqdO+/oiTVZZOATIltcLe2+0V/nDhD4nHnPTUjrD+X19JPuWYyEA5BpEUxE3wwQd5frBggxKyh1HkHo3UOqhCjybKNr3
  #       gilab.techmates.io ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMXO62AnEaPGyui6IhhQEfO1kwlYnbvxllX8UrMAC/GuRtATX+O3QfYHAGo0CN//74BQt46O9jhN2JiBWIvec0E=
  #       gilab.techmates.io ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIML+gRCc4bQjZEWeCtgGXNOyYco+Q6gMjTafUEcA9rEN
  #       gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
  #       gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
  #       gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      namespace: "argocd-system" 

dex:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      namespace: "argocd-system"

redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      namespace: "argocd-system"

server:
  extraArgs:
    - --insecure
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      namespace: "argocd-system"
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: http-cert-issuer
      traefik.ingress.kubernetes.io/router.middlewares: traefik-system-default@kubernetescrd
    hosts:
      - argo.iis-dev.net
    tls:
      - secretName: argocd-tls-certificate
        hosts:
          - argo.iis-dev.net

    # oidc.config: |
    #   name: AzureAD
    #   issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
    #   clientID: CLIENT_ID
    #   clientSecret: $oidc.azuread.clientSecret
    #   requestedIDTokenClaims:
    #     groups:
    #       essential: true
    #   requestedScopes:
    #     - openid
    #     - profile
    #     - email

repoServer:
  env: 
    - name: XDG_CONFIG_HOME
      value: /.config  
    - name: HELM_PLUGINS
      value: /custom-tools/helm-plugins/
    # - name: HELM_SECRETS_SOPS_PATH
    #   value: /custom-tools/sops
    - name: HELM_SECRETS_KUBECTL_PATH
      value: /custom-tools/kubectl
    - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
      value: "false"
    - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
      value: "false"
    - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
      value: "true"
    - name: HELM_SECRETS_CURL_PATH
      value: /custom-tools/curl
    - name: HELM_SECRETS_URL_VARIABLE_EXPANSION
      value: "true"
    - name: HELM_SECRETS_IGNORE_MISSING_VALUES
      value: "true"

  volumeMounts: 
    # - mountPath: /usr/local/bin/kustomize
    #   name: custom-tools
    #   subPath: kustomize
    # - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
    #   name: custom-tools
    #   subPath: ksops
    - mountPath: /custom-tools
      name: custom-tools
  volumes:
    - name: custom-tools
      emptyDir: {}
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      namespace: "argocd-system"

  clusterAdminAccess:
    enabled: true

  initContainers:
# ksops - for any sops secret used with kustomization
    # - name: install-ksops
    #   image: viaductoss/ksops:v4.1.0
    #   command: ["/bin/sh", "-c"]
    #   args:
    #     - echo "Installing KSOPS...";
    #       mv ksops /custom-tools/;
    #       mv $GOPATH/bin/kustomize /custom-tools/;
    #       echo "Done.";
    #   volumeMounts:
    #     - mountPath: /custom-tools
    #       name: custom-tools
# helm secrets - for helm values files     
    - name: download-tools
      image: alpine:latest
      command: [sh, -ec]
      env:
        - name: HELM_SECRETS_VERSION
          value: "4.2.0"
        - name: KUBECTL_VERSION
          value: "1.24.7"
        # - name: SOPS_VERSION
        #   value: "3.7.3"
      args:
        # - |
        #   mkdir -p /custom-tools/helm-plugins
        #   wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;
        #   wget -qO /custom-tools/sops https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux
        #   wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
        #   wget -qO /custom-tools/curl https://github.com/moparisthebest/static-curl/releases/download/v7.86.0/curl-amd64
        #   chmod +x /custom-tools/*
        - |
          mkdir -p /custom-tools/helm-plugins
          wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;
          wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
          wget -qO /custom-tools/curl https://github.com/moparisthebest/static-curl/releases/download/v7.86.0/curl-amd64
          chmod +x /custom-tools/*
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools


applicationSet:
  logFormat: "json"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      namespace: "argocd-system"

notifications:
  logFormat: "json"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      namespace: argocd-system