# Service wide configuration
metadata:
  appName: sidlo
  branch: main
  partOf: app-sidlo
  namespace: app-sidlo
  component: web

replicas: 1

# Transparent proxy configuration
ingress:
  host: sidlo.skusdev.net
  domain: skusdev.net
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: http-cert-issuer

api:
  url: http://sidlo.skusdev.net

container:
  port: 80
  image:
    repository: europe-central2-docker.pkg.dev/playgroundmain/sidlo/app
    tag: latest
