# Service wide configuration
metadata:
  appName: sidlo
  branch: main
  partOf: app-sidlo
  namespace: app-sidlo
  component: web

replicas: 1

# Transparent proxy configuration
ingress:
  hosts:
    - host: sidlo.skusdev.net
      paths:
        - path: /
          pathType: Prefix
    - host: sidlo-test.inforo.sk
      paths:
        - path: /
          pathType: Prefix
  domain: skusdev.net
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: http-cert-issuer

api:
  urls:
    - http://sidlo.skusdev.net
    - http://sidlo-test.inforo.sk

container:
  port: 80
  image:
    repository: gcr.io/playgroundmain/sidlo
    tag: latest
