apiVersion: v1
kind: Secret
metadata:
  # toto potom premenovat
  name: repo-https-github-com-idpsycho-iac
  namespace: argocd-system
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/idpsycho/iac.git
  username: rsekerka-dev-argo
  password: ghp_HAF6________________TAJNE____
  
