apiVersion: v1
kind: Secret
metadata:
  # toto potom premenovat
  name: repo-https-github-com-wiseman88-iac
  namespace: argocd-system
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/wiseman88/iac.git
  username: wiseman88-dev-argo
  password: ghp_HAF6________________TAJNE____
  
