podDisruptionBudget:
  enabled: true
  minAvailable: 1
ingressClass:
  enabled: true
  isDefaultClass: true
  fallbackApiVersion: v1
ingressRoute:
  dashboard:
    enabled: false
providers:
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    ingressClass: traefik
    publishedService:
      enabled: true
logs:
  general:
    format: json
    level: DEBUG
  access:
    enabled: true

ports:
  gitlab-ssh:
    port: 22
    expose: true

# service:
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: nlb
# service:
#   annotations:
#     cloud.google.com/load-balancer-type: "External"
#     # neviem ci je lespie toto, alebo to robis cez controlplane v googli
#     # kubernetes.io/ingress.global-static-ip-name: "34.116.242.146"
#     # kubernetes.io/ingress.global-static-ip-name: "kubedev-static"
# service:
#   type: LoadBalancer
#   annotations:
#     networking.gke.io/load-balancer-type: "External"
#     cloud.google.com/load-balancer-ip: "<YOUR-STATIC-IP-ADDRESS>"
service:
  type: LoadBalancer
  loadBalancerIP: 34.118.16.170
  annotations:
    networking.gke.io/load-balancer-type: "External"
    # nepouziva to tu ipcku vobec..
    kubernetes.io/ingress.global-static-ip-name: "my-static-ip"
  # spec:
  #   loadBalancerIP: 34.128.186.29


securityContext:
  runAsNonRoot: false
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsUser: 0

resources:
  requests:
    cpu: "50m" # som docasne znizil zo 100m, lebo mi to nejako neslo, vraj zral prazdny system 900, a bolo to cez limit..
    memory: "50Mi"
  limits:
    cpu: "300m"
    memory: "150Mi"