apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-test
  namespace: argocd-system
spec:
  generators:
  - list:
      elements:
      - name: test
  template:
    metadata:
      name: 'app-test'
      namespace: argocd-system
    spec:
      project: default
      source:
        repoURL: 'https://github.com/wiseman88/iac.git'
        targetRevision: HEAD
        path: '3-app-charts/test/chart'
        helm:
          valueFiles:
          - '../values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'app-test'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
