{{ $host := .Values.ingress.host | default (printf "%s.%s" (toString .Values.metadata.branch) (toString .Values.ingress.domain)) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.metadata.appName }}
  labels:
    {{- include "_snippet-labels" . | nindent 4 }}
    {{- include "_snippet-labels-version" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{ toYaml .Values.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ $host }}-tls
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.metadata.appName }}
                port:
                  number: {{ .Values.container.port }}
