# Service wide configuration
metadata:
  appName: sidlo-admin
  branch: main
  partOf: app-sidlo-admin
  namespace: app-sidlo-admin
  component: web

replicas: 1

# Transparent proxy configuration
ingress:
  host: sidlo-admin.skusdev.net
  domain: skusdev.net
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: http-cert-issuer

api:
  url: http://sidlo-admin.skusdev.net

container:
  port: 80
  image:
    repository: gcr.io/playgroundmain/sidlo-admin
    tag: latest
