apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-cert-issuer
spec:
  acme:
    privateKeySecretRef:
      name: http-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: traefik
